# Generated by Django 5.0.6 on 2024-06-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('a', 'Another color'), ('r', 'Red'), ('g', 'Green'), ('b', 'Blue'), ('y', 'Yellow'), ('o', 'Orange'), ('p', 'Purple'), ('w', 'White'), ('bk', 'Black'), ('gr', 'Gray'), ('br', 'Brown'), ('pk', 'Pink'), ('t', 'Turquoise')], default='a', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='company_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='deep',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.PositiveIntegerField(default=90),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(choices=[('a', 'Another material'), ('w', 'Wood'), ('i', 'Iron'), ('m', 'Marble'), ('g', 'Granite'), ('s', 'Soapstone'), ('q', 'Quartz'), ('c', 'Cotton'), ('l', 'Linen'), ('v', 'Velvet'), ('mic', 'Microfiber'), ('p', 'Polyester')], default='a', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='style',
            field=models.CharField(choices=[('a', 'Another style'), ('mod', 'Modern'), ('cla', 'Classic'), ('tra', 'Traditional'), ('con', 'Contemporary'), ('rus', 'Rustic'), ('ind', 'Industrial'), ('far', 'Farmhouse'), ('min', 'Minimalist'), ('tran', 'Transitional'), ('boh', 'Bohemian')], default='a', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='watanty_duration',
            field=models.PositiveIntegerField(blank=True, default=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
