# Generated by Django 5.0.3 on 2024-06-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_order_products_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='shop.product'),
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
