# Generated by Django 5.0.3 on 2024-06-18 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_telegramuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramUser',
        ),
    ]
